# Generated by Django 4.2.2 on 2023-06-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarea',
            fields=[
                ('idetiqueta_tarea', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(choices=[('Trabajo', 'Trabajo'), ('Hogar', 'Hogar'), ('Estudios', 'Estudios'), ('Otros', 'Otros')], default='Trabajo', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('idestado_tarea', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_tarea', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('estado_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estadotarea')),
                ('etiqueta_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoriatarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
