# Generated by Django 4.2.2 on 2023-07-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tarea_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_vencimiento',
        ),
    ]
