# Generated by Django 4.2.2 on 2023-07-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_etiquetatarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name_plural': 'Tareas'},
        ),
    ]
