# Generated by Django 4.2.2 on 2023-07-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(default='2023-08-03'),
            preserve_default=False,
        ),
    ]
