# Generated by Django 4.2.2 on 2023-07-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_tarea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='etiqueta_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.etiquetatarea'),
        ),
    ]
