# Generated by Django 4.2.2 on 2023-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tarea_etiqueta_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='idtarea',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
