# Generated by Django 4.2.2 on 2023-07-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
    ]
