# Generated by Django 4.2.2 on 2023-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado_tarea',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=50),
        ),
    ]
