# Generated by Django 4.2.2 on 2023-07-02 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_tarea_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='etiqueta_tarea',
            field=models.ForeignKey(blank=True, default='Hogar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.etiquetatarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(blank=True, default='Baja', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.prioridad'),
        ),
    ]
